### ISSUE TITLE
Verificación de tu código

### ISSUE THREAD

**Issue by ivanjimenez** [alberto-85/RepasoJunio#2]
Yo he introducido los valores de una matriz 3x3:
1 ->intro
0 -> intro
0-> intro
0->intro
1->intro
0->intro
0->intro
0->intro
1->intro
y la calcula bien, cuál es el problema?

**Comment by alberto-85** [comment]
pense que en la misma linea introducía todos los valores de la matriz
asi:
1 1 1 1
por eso pensaba que entraba en un bucle infinito..pero no ..si que tiene
fin.

¿estaría así bien el ejercicio?

**Comment by ivanjimenez** [comment]
Haz las pruebas necesarias y así te aseguras de lo que estás haciendo está bien. Debes aprender a realizar las pruebas para comprobar el código que haces.
